### PR TITLE
Use Shift-Up & Shift-Down to navigate in lists

### PR DESCRIPTION
**Pull request by charbeljc**
Say your prompt is something like this, with `^` indicating your cursor position.
```
.[0].hosts[0]
        ^
```
if you type `Ctl-Down`, it will become

```
.[0].hosts[1]
        ^
```

### CODE REVIEW

**Review by ynqa — CHANGES_REQUESTED** [review]
@charbeljc Thank you so much for proposing the introduction of a new mechanism.

I have two points to mention:

- ctrl+{up, down} is often reserved for operations on the laptop side. For example, in the default settings of MacOS, pressing ctrl+up opens mission control. Since this cannot be interrupted, I recommend using a different key binding.
- In the current implementation, pressing ctrl+{up, down} continues to move forward even if it is ineffective. I would like to use a mechanism like a ring-buffer to make it cycle (for example, if there are 3 Arrays, pressing ctrl+down would move 0 -> 1 -> 2 -> 0).

**Comment by charbeljc** [comment]
Hi, I changed to shift-{up, down} and implemented cycling. Let me know what you think.

**Comment by ynqa** [comment]
@charbeljc Does this mean that the jq filter is evaluated twice in a single iteration?

If so, I would like to stop that because even now, given large data, the evaluation of a single jq filter can hang, and there's no benefit that justifies making it slower by evaluating the filter more than once.

- https://github.com/ynqa/jnv/issues/2

The strategy I have in mind is to improve `suggestions`. Currently, they are managed as a `Vec<String>`.

```rust
let suggestions = all_kinds
            .iter()
            .filter_map(|kind| kind.path())
            .map(|segments| {
                if segments.is_empty() {
                    ".".to_string()
                } else {
                    segments
                        .iter()
                        .map(|segment| match segment {
                            JsonPathSegment::Key(key) => {
                                if key.contains('.') || key.contains('-') || key.contains('@') {
                                    format!(".\"{}\"", key)
                                } else {
                                    format!(".{}", key)
                                }
                            }
                            JsonPathSegment::Index(index) => format!("[{}]", index),
                        })
                        .collect::<String>()
                }
            });
```

If the result of the filter currently points to an Array, I plan to make changes so that you can search through this `suggestions` by using Shift+up, down. This eliminates the need to evaluate the jq filter again.

**Comment by charbeljc** [comment]
This is not the exact same filter that's got evaluated. For instance, if your prompt is 
```
.[0].hosts[0]
              ^
```
We evaluate
```
.[0].hosts | length
```
Off course this don't change things performance wise... If you can achieve the samedi effect with enhanced suggestions, it would be great !

**Pull request closed without merging**
